export const StopPoints = {
  "Battersea Power Station Underground Station": "940GZZBPSUST",
  "Acton Town Underground Station": "940GZZLUACT",
  "Archway Underground Station": "940GZZLUACY",
  "Archway Station": "9400ZZLUACY2",
  "Aldgate East Underground Station": "940GZZLUADE",
  "Angel Underground Station": "940GZZLUAGL",
  "Angel Station": "9400ZZLUAGL2",
  "Aldgate Underground Station": "940GZZLUALD",
  "Alperton Underground Station": "940GZZLUALP",
  "Amersham Underground Station": "940GZZLUAMS",
  "Arnos Grove Underground Station": "940GZZLUASG",
  "Arsenal Underground Station": "940GZZLUASL",
  "Bromley-by-Bow Underground Station": "940GZZLUBBB",
  "Barbican Underground Station": "940GZZLUBBN",
  "Bounds Green Underground Station": "940GZZLUBDS",
  "Bounds Green": "9400ZZLUBDS2",
  "Becontree Underground Station": "940GZZLUBEC",
  "Barkingside Underground Station": "940GZZLUBKE",
  "Blackfriars Underground Station": "940GZZLUBKF",
  "Barking Underground Station": "940GZZLUBKG",
  "Buckhurst Hill Underground Station": "940GZZLUBKH",
  "Bethnal Green Underground Station": "940GZZLUBLG",
  "Bethnal Green": "9400ZZLUBLG2",
  "Balham Underground Station": "940GZZLUBLM",
  "Balham Station": "9400ZZLUBLM2",
  "Blackhorse Road Underground Station": "940GZZLUBLR",
  "Blackhorse Road Station": "9400ZZLUBLR2",
  "Bermondsey Underground Station": "940GZZLUBMY",
  "Bond Street Underground Station": "940GZZLUBND",
  "Bond Street Station": "9400ZZLUBND4",
  "Bank Underground Station": "940GZZLUBNK",
  "Borough Underground Station": "940GZZLUBOR",
  "Boston Manor Underground Station": "940GZZLUBOS",
  "Barons Court Underground Station": "940GZZLUBSC",
  "Baker Street Underground Station": "940GZZLUBST",
  "Burnt Oak Underground Station": "940GZZLUBTK",
  "Burnt Oak Station": "9400ZZLUBTK2",
  "Brent Cross Underground Station": "940GZZLUBTX",
  "Brent Cross Station": "9400ZZLUBTX2",
  "Bow Road Underground Station": "940GZZLUBWR",
  "Bayswater Underground Station": "940GZZLUBWT",
  "Brixton Underground Station": "940GZZLUBXN",
  "Belsize Park Underground Station": "940GZZLUBZP",
  "Chalfont & Latimer Underground Station": "940GZZLUCAL",
  "Caledonian Road Underground Station": "940GZZLUCAR",
  "Caledonian Road Station": "9400ZZLUCAR2",
  "Chalk Farm Underground Station": "940GZZLUCFM",
  "Chalk Farm Station": "9400ZZLUCFM2",
  "Covent Garden Underground Station": "940GZZLUCGN",
  "Canning Town Underground Station": "940GZZLUCGT",
  "Chancery Lane Underground Station": "940GZZLUCHL",
  "Charing Cross Underground Station": "940GZZLUCHX",
  "Cockfosters Underground Station": "940GZZLUCKS",
  "Colindale Underground Station": "940GZZLUCND",
  "Colindale Station": "9400ZZLUCND2",
  "Clapham Common Underground Station": "940GZZLUCPC",
  "Clapham Common": "9400ZZLUCPC2",
  "Canons Park Underground Station": "940GZZLUCPK",
  "Clapham North Underground Station": "940GZZLUCPN",
  "Clapham North": "9400ZZLUCPN2",
  "Clapham South Underground Station": "940GZZLUCPS",
  "Clapham South": "9400ZZLUCPS2",
  "Colliers Wood Underground Station": "940GZZLUCSD",
  "Colliers Wood Station": "9400ZZLUCSD2",
  "Chesham Underground Station": "940GZZLUCSM",
  "Cannon Street Underground Station": "940GZZLUCST",
  "Camden Town Underground Station": "940GZZLUCTN",
  "Chigwell Underground Station": "940GZZLUCWL",
  "Chiswick Park Underground Station": "940GZZLUCWP",
  "Canada Water Underground Station": "940GZZLUCWR",
  "Croxley Underground Station": "940GZZLUCXY",
  "Chorleywood Underground Station": "940GZZLUCYD",
  "Canary Wharf Underground Station": "940GZZLUCYF",
  "Debden Underground Station": "940GZZLUDBN",
  "Dagenham East Underground Station": "940GZZLUDGE",
  "Dagenham Heathway Underground Station": "940GZZLUDGY",
  "Dollis Hill Underground Station": "940GZZLUDOH",
  "Dollis Hill Station": "9400ZZLUDOH2",
  "Elephant & Castle Underground Station": "940GZZLUEAC",
  "Eastcote Underground Station": "940GZZLUEAE",
  "East Acton Underground Station": "940GZZLUEAN",
  "Ealing Broadway Underground Station": "940GZZLUEBY",
  "Ealing Common Underground Station": "940GZZLUECM",
  "Earl's Court Underground Station": "940GZZLUECT",
  "East Finchley Underground Station": "940GZZLUEFY",
  "Edgware Underground Station": "940GZZLUEGW",
  "East Ham Underground Station": "940GZZLUEHM",
  "Embankment Underground Station": "940GZZLUEMB",
  "Epping Underground Station": "940GZZLUEPG",
  "Elm Park Underground Station": "940GZZLUEPK",
  "Elm Park Station": "9400ZZLUEPK2",
  "East Putney Underground Station": "940GZZLUEPY",
  "Edgware Road (Bakerloo) Underground Station": "940GZZLUERB",
  "Edgware Road (Circle Line) Underground Station": "940GZZLUERC",
  "Euston Square Underground Station": "940GZZLUESQ",
  "Euston Underground Station": "940GZZLUEUS",
  "Fulham Broadway Underground Station": "940GZZLUFBY",
  "Farringdon Underground Station": "940GZZLUFCN",
  "Fairlop Underground Station": "940GZZLUFLP",
  "Finsbury Park Underground Station": "940GZZLUFPK",
  "Finchley Central Underground Station": "940GZZLUFYC",
  "Finchley Road Underground Station": "940GZZLUFYR",
  "Gunnersbury Underground Station": "940GZZLUGBY",
  "Gunnersbury Station": "9400ZZLUGBY2",
  "Goodge Street Underground Station": "940GZZLUGDG",
  "Goodge Street Station": "9400ZZLUGDG2",
  "Greenford Underground Station": "940GZZLUGFD",
  "Grange Hill Underground Station": "940GZZLUGGH",
  "Golders Green Underground Station": "940GZZLUGGN",
  "Goldhawk Road Underground Station": "940GZZLUGHK",
  "Green Park Underground Station": "940GZZLUGPK",
  "Green Park Station": "9400ZZLUGPK6",
  "Great Portland Street Underground Station": "940GZZLUGPS",
  "Gants Hill Underground Station": "940GZZLUGTH",
  "Gants Hill Station": "9400ZZLUGTH2",
  "Gloucester Road Underground Station": "940GZZLUGTR",
  "Highbury & Islington Underground Station": "940GZZLUHAI",
  "Harrow & Wealdstone Underground Station": "940GZZLUHAW",
  "Holborn Underground Station": "940GZZLUHBN",
  "High Barnet Underground Station": "940GZZLUHBT",
  "Hornchurch Underground Station": "940GZZLUHCH",
  "Hendon Central Underground Station": "940GZZLUHCL",
  "Hendon Central Station": "9400ZZLUHCL2",
  "Hillingdon Underground Station": "940GZZLUHGD",
  "Hanger Lane Underground Station": "940GZZLUHGR",
  "Hanger Lane Station": "9400ZZLUHGR2",
  "Highgate Underground Station": "940GZZLUHGT",
  "Hainault Underground Station": "940GZZLUHLT",
  "Hatton Cross Underground Station": "940GZZLUHNX",
  "Hatton Cross Station": "9400ZZLUHNX2",
  "Harrow-on-the-Hill Underground Station": "940GZZLUHOH",
  "Hyde Park Corner Underground Station": "940GZZLUHPC",
  "Hyde Park Corner": "9400ZZLUHPC2",
  "Holland Park Underground Station": "940GZZLUHPK",
  "Heathrow Terminal 4 Underground Station": "940GZZLUHR4",
  "Heathrow Terminal 5 Underground Station": "940GZZLUHR5",
  "Heathrow Terminals 2 & 3 Underground Station": "940GZZLUHRC",
  "Heathrow Terminals 1-2-3 Underground Station": "9400ZZLUHRC2",
  "Hammersmith (H&C Line) Underground Station": "940GZZLUHSC",
  "Hammersmith (Dist&Picc Line) Underground Station": "940GZZLUHSD",
  "High Street Kensington Underground Station": "940GZZLUHSK",
  "Harlesden Underground Station": "940GZZLUHSN",
  "Hampstead Underground Station": "940GZZLUHTD",
  "Hounslow Central Underground Station": "940GZZLUHWC",
  "Hounslow Central Station": "9400ZZLUHWC2",
  "Hounslow East Underground Station": "940GZZLUHWE",
  "Hounslow West Underground Station": "940GZZLUHWT",
  "Hounslow West Station": "9400ZZLUHWT2",
  "Holloway Road Underground Station": "940GZZLUHWY",
  "Holloway Road Station": "9400ZZLUHWY2",
  "Ickenham Underground Station": "940GZZLUICK",
  "Kilburn Underground Station": "940GZZLUKBN",
  "Kingsbury Underground Station": "940GZZLUKBY",
  "Kenton Underground Station": "940GZZLUKEN",
  "Knightsbridge Underground Station": "940GZZLUKNB",
  "Kennington Underground Station": "940GZZLUKNG",
  "Kensington (Olympia) Underground Station": "940GZZLUKOY",
  "Kilburn Park Underground Station": "940GZZLUKPK",
  "Kilburn Park Station": "9400ZZLUKPK2",
  "Kentish Town Underground Station": "940GZZLUKSH",
  "Kensal Green Underground Station": "940GZZLUKSL",
  "King's Cross St. Pancras Underground Station": "940GZZLUKSX",
  "Kew Gardens Underground Station": "940GZZLUKWG",
  "Ladbroke Grove Underground Station": "940GZZLULAD",
  "Lambeth North Underground Station": "940GZZLULBN",
  "Lambeth North": "9400ZZLULBN2",
  "Loughton Underground Station": "940GZZLULGN",
  "Lancaster Gate Underground Station": "940GZZLULGT",
  "Lancaster Gate Station": "9400ZZLULGT2",
  "London Bridge Underground Station": "940GZZLULNB",
  "London Bridge Station": "9400ZZLULNB4",
  "Latimer Road Underground Station": "940GZZLULRD",
  "Leicester Square Underground Station": "940GZZLULSQ",
  "Liverpool Street Underground Station": "940GZZLULVT",
  "Leyton Underground Station": "940GZZLULYN",
  "Leytonstone Underground Station": "940GZZLULYS",
  "Marble Arch Underground Station": "940GZZLUMBA",
  "Marble Arch": "9400ZZLUMBA2",
  "Morden Underground Station": "940GZZLUMDN",
  "Mile End Underground Station": "940GZZLUMED",
  "Moorgate Underground Station": "940GZZLUMGT",
  "Mill Hill East Underground Station": "940GZZLUMHL",
  "Monument Underground Station": "940GZZLUMMT",
  "Moor Park Underground Station": "940GZZLUMPK",
  "Manor House Underground Station": "940GZZLUMRH",
  "Manor House": "9400ZZLUMRH2",
  "Mansion House Underground Station": "940GZZLUMSH",
  "Mornington Crescent Underground Station": "940GZZLUMTC",
  "Mornington Crescent": "9400ZZLUMTC2",
  "Maida Vale Underground Station": "940GZZLUMVL",
  "Maida Vale Station": "9400ZZLUMVL2",
  "Marylebone Underground Station": "940GZZLUMYB",
  "North Acton Underground Station": "940GZZLUNAN",
  "Newbury Park Underground Station": "940GZZLUNBP",
  "Neasden Underground Station": "940GZZLUNDN",
  "Neasden Station": "9400ZZLUNDN2",
  "North Ealing Underground Station": "940GZZLUNEN",
  "Northfields Underground Station": "940GZZLUNFD",
  "North Greenwich Underground Station": "940GZZLUNGW",
  "North Harrow Underground Station": "940GZZLUNHA",
  "Notting Hill Gate Underground Station": "940GZZLUNHG",
  "Northolt Underground Station": "940GZZLUNHT",
  "Northolt Station": "9400ZZLUNHT2",
  "Northwick Park Underground Station": "940GZZLUNKP",
  "Northwick Park Station": "9400ZZLUNKP2",
  "Northwood Underground Station": "940GZZLUNOW",
  "Northwood Hills Underground Station": "940GZZLUNWH",
  "North Wembley Underground Station": "940GZZLUNWY",
  "Oakwood Underground Station": "940GZZLUOAK",
  "Oakwood Station": "9400ZZLUOAK2",
  "Old Street Underground Station": "940GZZLUODS",
  "Old Street Station": "9400ZZLUODS2",
  "Osterley Underground Station": "940GZZLUOSY",
  "Oval Underground Station": "940GZZLUOVL",
  "Oxford Circus Underground Station": "940GZZLUOXC",
  "Paddington Underground Station": "940GZZLUPAC",
  "Paddington (H&C Line)-Underground": "940GZZLUPAH",
  "Piccadilly Circus Underground Station": "940GZZLUPCC",
  "Pimlico Underground Station": "940GZZLUPCO",
  "Pimlico Station": "9400ZZLUPCO2",
  "Park Royal Underground Station": "940GZZLUPKR",
  "Plaistow Underground Station": "940GZZLUPLW",
  "Pinner Underground Station": "940GZZLUPNR",
  "Preston Road Underground Station": "940GZZLUPRD",
  "Preston Road Station": "9400ZZLUPRD2",
  "Parsons Green Underground Station": "940GZZLUPSG",
  "Perivale Underground Station": "940GZZLUPVL",
  "Putney Bridge Underground Station": "940GZZLUPYB",
  "Queensbury Underground Station": "940GZZLUQBY",
  "Queen's Park Underground Station": "940GZZLUQPS",
  "Queensway Underground Station": "940GZZLUQWY",
  "Queensway Station": "9400ZZLUQWY2",
  "Redbridge Underground Station": "940GZZLURBG",
  "Redbridge Station": "9400ZZLURBG2",
  "Regent's Park Underground Station": "940GZZLURGP",
  "Rickmansworth Underground Station": "940GZZLURKW",
  "Richmond Underground Station": "940GZZLURMD",
  "Ruislip Gardens Underground Station": "940GZZLURSG",
  "Ruislip Gardens": "9400ZZLURSG2",
  "Ruislip Manor Underground Station": "940GZZLURSM",
  "Ruislip Underground Station": "940GZZLURSP",
  "Russell Square Underground Station": "940GZZLURSQ",
  "Ravenscourt Park Underground Station": "940GZZLURVP",
  "Roding Valley Underground Station": "940GZZLURVY",
  "Rayners Lane Underground Station": "940GZZLURYL",
  "Royal Oak Underground Station": "940GZZLURYO",
  "Royal Oak": "9400ZZLURYO2",
  "Shepherd's Bush (Central) Underground Station": "940GZZLUSBC",
  "Shepherd's Bush (Central Line)": "9400ZZLUSBC2",
  "Shepherd's Bush Market Underground Station": "940GZZLUSBM",
  "South Ealing Underground Station": "940GZZLUSEA",
  "Stamford Brook Underground Station": "940GZZLUSFB",
  "Southfields Underground Station": "940GZZLUSFS",
  "Southfields Station": "9400ZZLUSFS2",
  "Stepney Green Underground Station": "940GZZLUSGN",
  "Stonebridge Park Underground Station": "940GZZLUSGP",
  "Southgate Underground Station": "940GZZLUSGT",
  Southgate: "9400ZZLUSGT2",
  "South Harrow Underground Station": "940GZZLUSHH",
  "St. James's Park Underground Station": "940GZZLUSJP",
  "St. John's Wood Underground Station": "940GZZLUSJW",
  "St John's Wood Station": "9400ZZLUSJW2",
  "South Kensington Underground Station": "940GZZLUSKS",
  "South Kenton Underground Station": "940GZZLUSKT",
  "South Kenton Station": "9400ZZLUSKT2",
  "Stockwell Underground Station": "940GZZLUSKW",
  "Snaresbrook Underground Station": "940GZZLUSNB",
  "St. Paul's Underground Station": "940GZZLUSPU",
  "South Ruislip Underground Station": "940GZZLUSRP",
  "South Ruislip Station": "9400ZZLUSRP2",
  "Sloane Square Underground Station": "940GZZLUSSQ",
  "Stratford Underground Station": "940GZZLUSTD",
  "Stanmore Underground Station": "940GZZLUSTM",
  "Sudbury Hill Underground Station": "940GZZLUSUH",
  "Sudbury Town Underground Station": "940GZZLUSUT",
  "Seven Sisters Underground Station": "940GZZLUSVS",
  "Swiss Cottage Underground Station": "940GZZLUSWC",
  "Swiss Cottage Station": "9400ZZLUSWC2",
  "South Woodford Underground Station": "940GZZLUSWF",
  "Southwark Underground Station": "940GZZLUSWK",
  "South Wimbledon Underground Station": "940GZZLUSWN",
  "South Wimbledon Station": "9400ZZLUSWN2",
  "Totteridge & Whetstone Underground Station": "940GZZLUTAW",
  "Tooting Bec Underground Station": "940GZZLUTBC",
  "Tooting Bec Station": "9400ZZLUTBC2",
  "Tooting Broadway Underground Station": "940GZZLUTBY",
  "Tooting Broadway Station": "9400ZZLUTBY2",
  "Tottenham Court Road Underground Station": "940GZZLUTCR",
  "Tufnell Park Underground Station": "940GZZLUTFP",
  "Theydon Bois Underground Station": "940GZZLUTHB",
  "Tottenham Hale Underground Station": "940GZZLUTMH",
  "Tottenham Hale": "9400ZZLUTMH2",
  "Temple Underground Station": "940GZZLUTMP",
  "Turnham Green Underground Station": "940GZZLUTNG",
  "Turnpike Lane Underground Station": "940GZZLUTPN",
  "Turnpike Lane Station": "9400ZZLUTPN2",
  "Tower Hill Underground Station": "940GZZLUTWH",
  "Upminster Bridge Underground Station": "940GZZLUUPB",
  "Upminster Bridge": "9400ZZLUUPB2",
  "Upton Park Underground Station": "940GZZLUUPK",
  "Upminster Underground Station": "940GZZLUUPM",
  "Upney Underground Station": "940GZZLUUPY",
  "Upney Station": "9400ZZLUUPY2",
  "Uxbridge Underground Station": "940GZZLUUXB",
  "Victoria Underground Station": "940GZZLUVIC",
  "Vauxhall Underground Station": "940GZZLUVXL",
  Vauxhall: "9400ZZLUVXL2",
  "Watford Underground Station": "940GZZLUWAF",
  "West Brompton Underground Station": "940GZZLUWBN",
  "White City Underground Station": "940GZZLUWCY",
  "West Finchley Underground Station": "940GZZLUWFN",
  "West Ham Underground Station": "940GZZLUWHM",
  "West Hampstead Underground Station": "940GZZLUWHP",
  "West Harrow Underground Station": "940GZZLUWHW",
  "Willesden Green Underground Station": "940GZZLUWIG",
  "Willesden Green Station": "9400ZZLUWIG3",
  "Wimbledon Underground Station": "940GZZLUWIM",
  "Wimbledon Park Underground Station": "940GZZLUWIP",
  "Wimbledon Park": "9400ZZLUWIP2",
  "Willesden Junction Underground Station": "940GZZLUWJN",
  "Warwick Avenue Underground Station": "940GZZLUWKA",
  "Warwick Avenue": "9400ZZLUWKA2",
  "West Kensington Underground Station": "940GZZLUWKN",
  "Wood Lane Underground Station": "940GZZLUWLA",
  "Waterloo Underground Station": "940GZZLUWLO",
  "Waterloo Station": "9400ZZLUWLO8",
  "Woodford Underground Station": "940GZZLUWOF",
  "Wood Green Underground Station": "940GZZLUWOG",
  "Wood Green Station": "9400ZZLUWOG2",
  "Woodside Park Underground Station": "940GZZLUWOP",
  "Whitechapel Underground Station": "940GZZLUWPL",
  "West Ruislip Underground Station": "940GZZLUWRP",
  "Warren Street Underground Station": "940GZZLUWRR",
  "Wanstead Underground Station": "940GZZLUWSD",
  "Wanstead Station": "9400ZZLUWSD2",
  "Westminster Underground Station": "940GZZLUWSM",
  "Westbourne Park Underground Station": "940GZZLUWSP",
  "West Acton Underground Station": "940GZZLUWTA",
  "Walthamstow Central Underground Station": "940GZZLUWWL",
  "Wembley Central Underground Station": "940GZZLUWYC",
  "Wembley Park Underground Station": "940GZZLUWYP",
  "Nine Elms Underground Station": "940GZZNEUGST",
};
